### ISSUE TITLE
Widget in browsable API (for maxParticipants) allows selection of negative values

### ISSUE THREAD

**Issue by joncison** [joncison/ifbcat-sandbox#11]
The widget in the browsable API for ``maxParticipants`` field in ``Event`` model is allow a negative value to be selected, although the validation* works OK and prevents a negative value from being set.

It would be nice if the widget could be configured to not allow a negative value to be selected in the first place, rather, to only support values from 1 up.

[* on next commit, see below]

**Comment by joncison** [comment]
PS.  @bryan-brancotte I'm assuming that all validation logic should go (for now) in ``serializers.py`` as per suggestion in the [docs](https://www.django-rest-framework.org/api-guide/validators/#validation-in-rest-framework) (if I take the meaning correctly). With possibly some logic moved to it's own module in future refactoring, as needed.

The logic could have been added to ``models.py`` e.g.
``maxParticipants = models.PositiveSmallIntegerField(null=True, blank=True, validators=[MinValueValidator(1)], help_text="Maximum number of participants to the event.")``

but I didn't do that, for reason given above.

**Comment by bryan-brancotte** [comment]
Hi Jon,

The MinValueValidator should be in the model, and django rest framework (DRF) should take it into account (after all other like [django-crispy-forms](https://github.com/django-crispy-forms/django-crispy-forms/)). The issue here is that the template used to render the widget ignore if the field have a min or a validator (no min [here](https://github.com/encode/django-rest-framework/blob/master/rest_framework/templates/rest_framework/horizontal/input.html#L9)). 

With #12 I propose we patch the DRF, here after is the generated html for a field with a min defined :
```html
<div class="form-group ">  
    <label class="col-sm-2 control-label ">
        MaxParticipants
    </label>
    <div class="col-sm-10">
        <input name="maxParticipants" class="form-control" type="number" value="" min="1">
        <span class="help-block">Maximum number of participants to the event.</span>
    </div>
</div>
```
