### ISSUE TITLE
Ensure fields which are used for database look-up are defined as unique in models

### ISSUE THREAD

**Issue by joncison** [joncison/ifbcat-sandbox#91]
e.g. ``name`` is frequently used for database look-up, so this field should be unique in the appropriate model file.

**Comment by bryan-brancotte** [comment]
Each ModelViewSet in views.py using `lookup_field = 'XXX'` must be for a model where `XXX` is unique. 

EventViewSet is using lookup_field = 'name', but do we want to make impossible to have two event with the same full name ? As it is the full name maybe, but I prefer to raise the question.

**Comment by joncison** [comment]
Ah, well spotted.  It's probably asking for trouble to insist that Event and thus also TrainingEvent must have unique names - so for these we can just use the pk for look-up instead.   

I think the others are OK though.

A little clean-up is needed.

**Comment by bryan-brancotte** [comment]
Resource classes are in the same use case, do we make the name unique, or remove the lookup_field ?

**Comment by bryan-brancotte** [comment]
the `lookup_field='name'` is usefull for Resource as it indicate that all child class of Resource will be accessed by name, the issue is that we must make the name unique, and as Resource is not Abstract, the uniqueness is shared between all child classes (indeed a table is created in the db for Resource).

Two choices : 
 * do not lookup by name
 * make Resource abstract, and name uniq

I vote for the second choice, but all ComputingFacility and TrainingMaterial will be lost as the models have to be dropped from the DB. Also when I will start doing that I will have to be the only one pushing new migration to the git.

Are you ok with that @joncison ?

**Comment by bryan-brancotte** [comment]
After some test, making Resource abstract prevent accessing to ComputingFacility and TrainingMaterial in the same queryset. As TrainingMaterial, ComputingFacility, Database and Tool are object of a different nature, I think it is a good thing that they are not anymore in the same queryset, and handled as object of the same nature.

**Comment by joncison** [comment]
We do really need to lookup by name, especially (eventually) for database and tool, and I agree the different types of Resource really are distinct.  So option 2 gets my vote also.  The existing DB entries for ComputingFacility and TrainingMaterial can go.  

So I shouldn't make any changes that require a migration until you are done with it?

**Comment by bryan-brancotte** [comment]
Yes, that is the idea. I'm doing it now

**Comment by bryan-brancotte** [comment]
it's done !
